"""
Circuit JSON  →  Verilog-2001 netlist.

The exporter walks the same gate graph the simulator uses and emits a
synthesizable structural module:

    - INPUT / CLOCK / VCC / GND  →  module ports / constants
    - OUTPUT / LED               →  module output ports
    - Standard combinational gates (AND/OR/NOT/NAND/NOR/XOR/XNOR) →
      built-in Verilog primitives
    - Macros (HA / FA / MUX2 / MUX4 / DEC24 / DEC38 / ENC42 / CMP2 /
      DFF / JKFF / TFF / SRLATCH / REG4) → behavioural always-blocks

Output is plain-text Verilog ready to drop into Icarus/Verilator/Yosys.
The exporter is intentionally dependency-free (pure stdlib) and never
mutates the input circuit.
"""
from __future__ import annotations

from collections import defaultdict
from typing import Iterable


_COMBINATIONAL = {"AND", "OR", "NAND", "NOR", "XOR", "XNOR", "NOT"}
_VERILOG_PRIM = {            # 1:1 map to Verilog gate primitives
    "AND": "and", "OR": "or", "NAND": "nand", "NOR": "nor",
    "XOR": "xor", "XNOR": "xnor", "NOT": "not",
}
_MACRO_OUTPUTS = {           # number of output pins per macro
    "HA": 2, "FA": 2, "DFF": 2, "JKFF": 2, "TFF": 2, "SRLATCH": 2,
    "MUX2": 1, "MUX4": 1, "DEC24": 4, "DEC38": 8, "ENC42": 2,
    "CMP2": 1, "REG4": 4,
}


class VerilogExportError(ValueError):
    """Raised when a circuit can't be exported (e.g. unknown gate)."""


def _sanitize(name: str) -> str:
    """Verilog identifiers: leading letter/_, then alnum/_ only."""
    out = []
    for c in str(name):
        if c.isalnum() or c == "_":
            out.append(c)
        else:
            out.append("_")
    s = "".join(out) or "n"
    if not (s[0].isalpha() or s[0] == "_"):
        s = "n_" + s
    return s


def _wire_name(gid: str, pin: int = 0) -> str:
    base = _sanitize(gid)
    return f"w_{base}" if pin == 0 else f"w_{base}_{pin}"


def _gate_pin_inputs(gates: list[dict], wires: list[dict]) -> dict[str, dict[int, str]]:
    """For each gate id, return {input_pin → source_wire_name}."""
    by_dst: dict[str, dict[int, str]] = defaultdict(dict)
    for w in wires:
        src = w.get("from_gate") or w.get("fg")
        dst = w.get("to_gate") or w.get("tg")
        src_pin = int(w.get("from_pin") or w.get("fp") or 0)
        dst_pin = int(w.get("to_pin") or w.get("tp") or 0)
        if src is None or dst is None:
            continue
        by_dst[dst][dst_pin] = _wire_name(src, src_pin)
    return by_dst


def _ordered_inputs(inputs_by_pin: dict[int, str], expected: int) -> list[str]:
    """Return inputs in pin order, filling missing pins with 1'b0."""
    return [inputs_by_pin.get(i, "1'b0") for i in range(expected)]


def _arity(gate_type: str, inputs_by_pin: dict[int, str]) -> int:
    """How many input pins a gate uses. Combinational gates are variadic,
    so use the highest connected pin index + 1 (min 2 except NOT which is 1)."""
    t = gate_type.upper()
    if t == "NOT":
        return 1
    if t in {"AND", "OR", "NAND", "NOR", "XOR", "XNOR"}:
        if not inputs_by_pin:
            return 2
        return max(2, max(inputs_by_pin) + 1)
    # Macros have fixed arity:
    return {
        "HA": 2, "FA": 3, "MUX2": 3, "MUX4": 6, "DEC24": 2, "DEC38": 3,
        "ENC42": 4, "CMP2": 4, "DFF": 2, "JKFF": 3, "TFF": 2,
        "SRLATCH": 2, "REG4": 5,
    }.get(t, max((max(inputs_by_pin) + 1) if inputs_by_pin else 0, 1))


def export_verilog(circuit: dict, module_name: str = "logicgate_circuit") -> str:
    """Convert a {gates, wires} dict to a Verilog source string.

    Raises VerilogExportError on unknown gate types or empty circuits.
    """
    gates: list[dict] = list(circuit.get("gates") or [])
    wires: list[dict] = list(circuit.get("wires") or [])
    if not gates:
        raise VerilogExportError("Circuit has no gates")

    mod = _sanitize(module_name)
    inputs_by_dst = _gate_pin_inputs(gates, wires)

    # Categorize gates.
    inputs:  list[dict] = []
    outputs: list[dict] = []
    clocks:  list[dict] = []
    internal: list[dict] = []
    for g in gates:
        t = (g.get("type") or "").upper()
        if t == "INPUT":
            inputs.append(g)
        elif t == "CLOCK":
            clocks.append(g)
            inputs.append(g)      # CLK is also a port
        elif t in {"OUTPUT", "LED"}:
            outputs.append(g)
        else:
            internal.append(g)

    # Header — port list.
    in_ports  = [_sanitize(g["id"]) for g in inputs]
    out_ports = [_sanitize(g["id"]) for g in outputs]
    port_list = ", ".join(in_ports + out_ports) if (in_ports or out_ports) else ""

    L: list[str] = []
    L.append("// Generated by LogicGate — github.com/Suno706/logicgate")
    L.append("// Do not hand-edit; re-export from the editor instead.")
    L.append("`default_nettype none")
    L.append("")
    L.append(f"module {mod} ({port_list});")
    for p in in_ports:
        L.append(f"  input  wire {p};")
    for p in out_ports:
        L.append(f"  output wire {p};")
    L.append("")

    # Source wires (INPUT / CLOCK / VCC / GND).
    for g in inputs:
        gid = _sanitize(g["id"])
        L.append(f"  wire {_wire_name(g['id'])} = {gid};")
    for g in gates:
        t = (g.get("type") or "").upper()
        if t == "VCC":
            L.append(f"  wire {_wire_name(g['id'])} = 1'b1;")
        elif t == "GND":
            L.append(f"  wire {_wire_name(g['id'])} = 1'b0;")

    # Declare internal wires for every non-port gate output pin actually
    # produced (pin 0 always; macro extra pins as needed).
    declared: set[str] = set()
    for g in internal:
        t = (g.get("type") or "").upper()
        n_out = _MACRO_OUTPUTS.get(t, 1)
        for pin in range(n_out):
            name = _wire_name(g["id"], pin)
            if name not in declared:
                L.append(f"  wire {name};")
                declared.add(name)

    L.append("")

    # Emit gate instances.
    for g in internal:
        gid = g["id"]
        t = (g.get("type") or "").upper()
        ins = inputs_by_dst.get(gid, {})
        n = _arity(t, ins)
        ordered = _ordered_inputs(ins, n)

        if t in _COMBINATIONAL:
            prim = _VERILOG_PRIM[t]
            out = _wire_name(gid, 0)
            args = ", ".join([out, *ordered])
            L.append(f"  {prim} u_{_sanitize(gid)} ({args});")
            continue

        if t == "BUS":
            src = ordered[0] if ordered else "1'b0"
            L.append(f"  assign {_wire_name(gid)} = {src};")
            continue

        if t == "HA":
            a, b = ordered[0], ordered[1]
            L.append(f"  assign {_wire_name(gid, 0)} = {a} ^ {b};   // sum")
            L.append(f"  assign {_wire_name(gid, 1)} = {a} & {b};   // carry")
            continue

        if t == "FA":
            a, b, ci = ordered[0], ordered[1], ordered[2]
            L.append(f"  assign {_wire_name(gid, 0)} = {a} ^ {b} ^ {ci};")
            L.append(
                f"  assign {_wire_name(gid, 1)} = "
                f"({a} & {b}) | ({b} & {ci}) | ({a} & {ci});"
            )
            continue

        if t == "MUX2":
            a, b, s = ordered[0], ordered[1], ordered[2]
            L.append(f"  assign {_wire_name(gid, 0)} = {s} ? {b} : {a};")
            continue

        if t == "MUX4":
            d0, d1, d2, d3, s0, s1 = ordered[0:6]
            L.append(
                f"  assign {_wire_name(gid, 0)} = "
                f"({{ {s1}, {s0} }} == 2'd0) ? {d0} : "
                f"({{ {s1}, {s0} }} == 2'd1) ? {d1} : "
                f"({{ {s1}, {s0} }} == 2'd2) ? {d2} : {d3};"
            )
            continue

        if t == "DEC24":
            a, b = ordered[0], ordered[1]
            sel = f"{{ {a}, {b} }}"
            for i in range(4):
                L.append(f"  assign {_wire_name(gid, i)} = ({sel} == 2'd{i});")
            continue

        if t == "DEC38":
            a, b, c = ordered[0], ordered[1], ordered[2]
            sel = f"{{ {a}, {b}, {c} }}"
            for i in range(8):
                L.append(f"  assign {_wire_name(gid, i)} = ({sel} == 3'd{i});")
            continue

        if t == "ENC42":
            i0, i1, i2, i3 = ordered[0:4]
            L.append(f"  assign {_wire_name(gid, 1)} = {i3} | {i2};            // y1")
            L.append(f"  assign {_wire_name(gid, 0)} = {i3} | (~{i2} & {i1});  // y0")
            continue

        if t == "CMP2":
            a0, a1, b0, b1 = ordered[0:4]
            L.append(
                f"  assign {_wire_name(gid, 0)} = "
                f"({a0} == {b0}) && ({a1} == {b1});"
            )
            continue

        if t in {"DFF", "TFF", "JKFF", "SRLATCH", "REG4"}:
            # Behavioural — needs a clock. Find the first CLOCK gate; if
            # absent, fall back to the conventional pin (D-FF: pin 1, etc.).
            clk_wire = _wire_name(clocks[0]["id"]) if clocks else (
                ordered[1] if t == "DFF" else
                ordered[2] if t in {"JKFF", "REG4"} else
                ordered[0]
            )
            q = _wire_name(gid, 0)
            qn = _wire_name(gid, 1) if t != "REG4" else None
            reg_q = f"r_{_sanitize(gid)}"
            if t == "REG4":
                L.append(f"  reg [3:0] {reg_q} = 4'b0;")
                L.append(f"  always @(posedge {clk_wire}) {reg_q} <= "
                         f"{{ {ordered[3]}, {ordered[2]}, {ordered[1]}, {ordered[0]} }};")
                for i in range(4):
                    L.append(f"  assign {_wire_name(gid, i)} = {reg_q}[{i}];")
                continue

            L.append(f"  reg {reg_q} = 1'b0;")
            if t == "DFF":
                L.append(f"  always @(posedge {clk_wire}) {reg_q} <= {ordered[0]};")
            elif t == "JKFF":
                j, k = ordered[0], ordered[1]
                L.append(f"  always @(posedge {clk_wire}) {reg_q} <= "
                         f"({j} & ~{reg_q}) | (~{k} & {reg_q});")
            elif t == "TFF":
                tin = ordered[0]
                L.append(f"  always @(posedge {clk_wire}) "
                         f"{reg_q} <= {tin} ^ {reg_q};")
            elif t == "SRLATCH":
                s, r = ordered[0], ordered[1]
                L.append(f"  always @* begin")
                L.append(f"    if ({s} && !{r})      {reg_q} = 1'b1;")
                L.append(f"    else if ({r} && !{s}) {reg_q} = 1'b0;")
                L.append(f"  end")
            L.append(f"  assign {q} = {reg_q};")
            if qn:
                L.append(f"  assign {qn} = ~{reg_q};")
            continue

        # Anything else is an unsupported gate.
        raise VerilogExportError(f"Cannot export gate type: {g.get('type')}")

    L.append("")

    # Wire OUTPUT / LED ports up to their drivers.
    for g in outputs:
        gid = g["id"]
        ins = inputs_by_dst.get(gid, {})
        src = ins.get(0, "1'b0")
        L.append(f"  assign {_sanitize(gid)} = {src};")

    L.append("")
    L.append("endmodule")
    L.append("`default_nettype wire")
    return "\n".join(L) + "\n"


def export_summary(circuit: dict) -> dict:
    """Cheap metadata about an export — useful for the UI confirmation."""
    gates = circuit.get("gates") or []
    types: dict[str, int] = {}
    for g in gates:
        t = (g.get("type") or "").upper()
        types[t] = types.get(t, 0) + 1
    return {
        "gate_count":  len(gates),
        "wire_count":  len(circuit.get("wires") or []),
        "by_type":     types,
        "has_clock":   any((g.get("type") or "").upper() == "CLOCK" for g in gates),
        "sequential":  any((g.get("type") or "").upper() in _MACRO_OUTPUTS
                           and (g.get("type") or "").upper() in
                           {"DFF", "JKFF", "TFF", "SRLATCH", "REG4"}
                           for g in gates),
    }


__all__: Iterable[str] = ("export_verilog", "export_summary", "VerilogExportError")
